FROM node:latest as build
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm install
COPY . .
RUN npm run build

FROM nginx:1.21-alpine
COPY nginx.conf /etc/nginx/nginx.conf
COPY --from=build /app/dist/client-app /usr/share/nginx/html

# EXPOSE 4200

CMD ["nginx", "-g", "daemon off;"]
